apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: devops-api
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'devops-api'
        static_configs:
          - targets: ['devops-api-service:80']
        metrics_path: '/metrics'
